### ISSUE TITLE
Add support for row with the same value in all column in eigenWeightedMean

### ISSUE THREAD

**Issue by darsoo** [lianos/multiGSEA#20]
I'm working with FacileDataSet. While we are using `eigenWeightedMean`, we found that when `x` have the same value (eg. 0) for all column function will crash. It is related with `scale()` in `gsdScore`, which convert that row to NaN. 
We proposed two solutions for this:
1. Here we converting all NaN to 0 after scale, eg.
```
  xs <- t(scale(t(x), center=center, scale=scale))
  if(any(is.nan(xs))){
    warning("found NaN in 'x'. all NaN coverted to 0. Possible cause: at least one row has the same number in all column")
    xs[is.nan(xs)] <- 0
  } 
```
2. Firstly check if we have rows with the same value in all column, and next converting only that row.

We prefer the first solution. But the second solution is more accurate because we changing only rows with the described issue. But we not sure if it is possible to have only a few `NaN` instead of a row of `NaN` or have `NaN` from another reason. If not, the first solution will be safety and simpler.

**Comment by lianos** [comment]
Thanks for the report.

I'm at a bit of a crossroads as to how to properly handle this.

Currently, this situation is handled in the [scoreSingleSamples()](https://github.com/lianos/multiGSEA/blob/908a4e374093fac9a00045f8d88604ffab51612b/R/scoreSingleSamples.R#L92) function, where you can see that we:

1. First test the expression matrix for any genes with close-to-zero standard deviation
2. Remove such genes / rows from the matrix
3. Conform the genesets to the newly reduced expression matrix
4. Iterative over genesets and methods to score each sample based on all combinations of those two.

It would be pretty straight forward to extract that "remove low stddev genes" code block into a helper function, which the individual single-sample-scoring methods to use.

This still feels most correct to me. The problem is that if all of the genes have 0-ish sd, then this method will still throw an error ... in which case, adding your fix would be a good one.

I'll noodle on this for a bit, and drop one of this fixes soon. Thank you for the report and the suggested fix!
